
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	private global::Gtk.Fixed fixed2;
	private global::Gtk.Entry txtLogin;
	private global::Gtk.CheckButton chopengl;
	private global::Gtk.Button btnPlay;
	private global::Gtk.Button btnAutors;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = "MainWindow";
		this.WindowPosition = ((global::Gtk.WindowPosition)(3));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed2 = new global::Gtk.Fixed ();
		this.fixed2.Name = "fixed2";
		this.fixed2.HasWindow = false;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.txtLogin = new global::Gtk.Entry ();
		this.txtLogin.CanFocus = true;
		this.txtLogin.Name = "txtLogin";
		this.txtLogin.Text = "login";
		this.txtLogin.IsEditable = true;
		this.txtLogin.InvisibleChar = '●';
		this.fixed2.Add (this.txtLogin);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.txtLogin]));
		w2.X = 15;
		w2.Y = 15;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.chopengl = new global::Gtk.CheckButton ();
		this.chopengl.CanFocus = true;
		this.chopengl.Name = "chopengl";
		this.chopengl.Label = "-opengl";
		this.chopengl.Active = true;
		this.chopengl.DrawIndicator = true;
		this.chopengl.UseUnderline = true;
		this.fixed2.Add (this.chopengl);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.chopengl]));
		w3.X = 180;
		w3.Y = 15;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.btnPlay = new global::Gtk.Button ();
		this.btnPlay.CanFocus = true;
		this.btnPlay.Name = "btnPlay";
		this.btnPlay.UseUnderline = true;
		this.btnPlay.Label = "odpalaj giere !";
		this.fixed2.Add (this.btnPlay);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.btnPlay]));
		w4.X = 15;
		w4.Y = 45;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.btnAutors = new global::Gtk.Button ();
		this.btnAutors.CanFocus = true;
		this.btnAutors.Name = "btnAutors";
		this.btnAutors.UseUnderline = true;
		this.btnAutors.Label = "O Programie";
		this.fixed2.Add (this.btnAutors);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.btnAutors]));
		w5.X = 160;
		w5.Y = 45;
		this.Add (this.fixed2);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 263;
		this.DefaultHeight = 87;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.btnPlay.Clicked += new global::System.EventHandler (this.OnBtnPlayClicked);
		this.btnAutors.Clicked += new global::System.EventHandler (this.OnBtnAutorsClicked);
	}
}
